//este archivo se hace gracias a la extension REST Client sirve para probar request
//request = metodo + url
PUT http://localhost:3000/cursos/programacion/2
Content-Type: application/json

{
    "id": 2,
    "titulo": "Aprende Node.js",
    "lenguaje": "javascript",
    "vistas": 4578,
    "nivel": "basico"
}