//este archivo se hace gracias a la extension REST Client sirve para probar request
//request = metodo + url
POST http://localhost:3000/cursos/programacion
Content-Type: application/json

{
    "titulo": "El misterioso hombre de negro"
}
